### ISSUE TITLE
LCFS - IDIR users can edit organization information

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#165]
Description:
IDIR users can now edit existing organizations. This feature includes:

1. Adding an Edit pencil icon on the Organizations Details page.
2. Making the icon only visible to IDIR users with the Administrator role.
3. Ensuring that clicking on the pencil icon takes the IDIR user to the Edit organization page.
4. The Edit organization page is identical to the 'create organization' page but is prepopulated with the organization's information.
5. Maintaining the distinction between required and optional fields from the 'create organization' page.
6. Allowing the fields to be editable by the IDIR user.
7. Including Save and Back buttons where clicking on Save updates the record in the database, and redirects the user back to the Organization Details page.
8. Implementing breadcrumb navigation on this page.

Wireframes:
- Organization page (pencil icon link to get to the Edit Org page): [Link to wireframe](https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164774350)
- Edit Organization page: [Link to wireframe](https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164728479)

Purpose and benefit to user:
This functionality allows IDIR users to effectively manage and update organization information as needed, ensuring data accuracy and relevancy.

Acceptance Criteria:
1. Given I am an IDIR user with Administrator role, When I navigate to the Organization Details page, then I should see an Edit pencil icon.
2. Given I am an IDIR user with Administrator role, When I click the Edit pencil icon, then I should be taken to the Edit Organization page.
3. Given I am on the Edit Organization page, When I edit the fields and click Save, then the changes should be updated in the database and I should be redirected to the Organization Details page.

Development Checklist:
- [x] Implement the Edit pencil icon on the Organization Details page.
- [x] Ensure visibility of the icon is restricted to IDIR users with the Administrator role.
- [x] Link the Edit pencil icon to the Edit Organization page.
- [x] Enable pre-population of organization data on the Edit Organization page.
- [x] Maintain the integrity of required and optional fields.
- [ ] Implement Save and Back functionality.
- [ ] Add breadcrumb navigation on the Edit Organization page.
- [ ] Write unit tests to cover validation logic
- [ ] Write Cypress end to end test proving edit of organization works.

Notes:
- Ensure that the Edit functionality adheres to existing security and data handling protocols.
- Testing should include verification of user role restrictions and data integrity post-edit.
- The UI/UX should be consistent with the existing design language of the platform.

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/165?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/165?planning-poker) with Zenhub @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
When 'edit' pencil icon is pressed, the next page the IDIR user is taken to does not show anything other than the disclaimer and the title 'Edit Organization'. Please see screenshot:


![Image](https://github.com/bcgov/lcfs/assets/156380046/69846b82-721d-4dad-bf28-c0a7ed05223c)

**Comment by kevin-hashimoto** [comment]
@AlexZorkin fixed via another ticket
issue: the edit route was displaying the wrong component

**Comment by Grulin** [comment]
As an IDIR user, I can access the edit organization page and make changes, but when I hit save, the following fields show an error: Address for service postal code, address in B.C. street address, address in B.C. city and address in B.C. postal code.

Please see screenshot for error example:


![Image](https://github.com/bcgov/lcfs/assets/156380046/6dc36bcc-9ac6-44eb-bbb2-539429e21bb3)

**Comment by justin-lepitzki** [comment]
@Grulin I think the address in BC errors are appearing because you either need to fill out the address information or select the "Same as address for service" check box.

**Comment by Grulin** [comment]
@justin-lepitzki  Correct. Sorry, I should have clarified I was still getting the error even with the "Same as address for service" option chosen.

**Comment by hamed-valiollahi** [comment]
@Grulin Thanks Lindsy for your comments.

## Resolved Issues

1. Fixed the issue where the "Operating Name of Organization" value was not loading correctly in the edit organization form.
2. Addressed the problem with loading "Address in B.C." values in the edit organization form.
3. Implemented auto-check for "Same as Legal Name" and "Same as Address for Service" checkboxes during the initial load in the edit organization form.
4. Eliminated redundant validation errors for "Address in B.C." fields when "Same as Address for Service" is selected.

Also, I can confirm that the postal code validation works for both Canadian postal codes (with or without space) and US postal codes.

**Comment by Grulin** [comment]
Works for every organization except LCFS Ord 2. Issue addressed in separate card #467
