### ISSUE TITLE
LCFS - Export fuel schedule updates

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#2215]
**Description:**  
Enhance the Export fuel schedule by modifying the placement and behavior of the ‘Export date’ field, updating the ‘Determining CI’ options, and implementing an alternate RCI lookup when necessary.

**Wireframe:**  
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/201433209

**Purpose and benefit to user:**  
These changes enhance the Export fuel schedule by improving more accurate carbon intensity (CI) calculations.

**Acceptance Criteria:**  
- [x] Move the ‘Export date’ field to appear after the ‘Fuel code’ select list.
- [x] Disable the ‘Export date’ field by default.
- [x] Make Export date optional unless Unknown is selected from Determining CI, then it is required.
- [x] Add ‘Unknown’ as an option in the ‘Determining CI’ dropdown.
- [x] If ‘Unknown’ is selected:
  - [x] The ‘Fuel code’ field remains disabled.
  - [x] The ‘Export date’ field is enabled.
  - [x] Entering an ‘Export date’ triggers an alternate RCI lookup.
- [x] The RCI lookup queries all active fuel codes for the selected fuel from the 12 months prior to the Export date.
- [ ] The system selects the lowest CI value from the queried results and applies it.
- [ ] Validate that all changes integrate seamlessly into the existing Export Fuel Schedule workflow.

**Development Checklist:**  
- [ ] Adjust UI placement of the ‘Export date’ field.
- [ ] Adjust database so the Export date is optional
- [ ] Implement logic to disable/enable fields based on ‘Determining CI’ selection.
- [ ] Configure the alternate RCI lookup query.
- [ ] Ensure the lowest CI value is correctly applied when ‘Unknown’ is selected.

**Notes:**  
- Ensure error handling is in place for scenarios where no CI values are found within the 12-month range.

**Comment by hamed-valiollahi** [comment]
The following are addressed as part of this ticket:
- RCI selection for ‘Fuel code - Section 19 (b) (i)’ now correctly pulls the CI from the selected fuel code instead of defaulting to the fuel type CI.
- quantity_must_be_positive validation now correctly prevents negative or zero values.

**Comment by airinggov** [comment]
When selecting a fuel code or the default CI the Export date should remain locked/disabled/grey.
When selecting Unknown and entering a date, it throws a 500 error and never saves the row.

**Comment by hamed-valiollahi** [comment]
> When selecting a fuel code or the default CI the Export date should remain locked/disabled/grey. When selecting Unknown and entering a date, it throws a 500 error and never saves the row.

Hi @airinggov , Thanks for testing. I’ll look into this issue and resolve it today. Next time, I’ll test my tickets on both dev and local to avoid this kind of issue. Not exactly sure what the problem is! Probably the two tickets are impacting each other.

Regarding the first issue, Sorry, my understanding from the ticket was that it's optional for all acts except "Unknown".

**Comment by hamed-valiollahi** [comment]
Good morning @airinggov , I’ve fixed both reported issues. I noticed that the 500 error was happening when there’s no valid fuel code in the 12 months prior to the selected export date. In that case, I’ve added an error message to let the user know they need to adjust the export date. Thanks for your thorough testing!

**Comment by airinggov** [comment]
@hamed-valiollahi thanks Hamed, instead of the error message can we just then set the RCI to the Default value?

**Comment by hamed-valiollahi** [comment]
@airinggov Of course!, I'll apply that today.

**Comment by Grulin** [comment]
This is looking so close @hamed-valiollahi . I have 2 comments: 

1) The Export Date column is still showing in the incorrect place on the main summary page. This column should be moved in this view as well:

![Image](https://github.com/user-attachments/assets/749cece7-c7dd-4d4b-9f1f-7897167f3e4c)

2) I tested how this would update for the 12 month RCI lookup if I went and added an effective code with a lower CI. The good news is, it worked as expected when I went back in to the Export section and updated it and saved it, the bad news is that it also did not reflect in the summary view of this report section: 

This is the input grid for the Export section with the correct new updated RCI:

![Image](https://github.com/user-attachments/assets/44a58e70-b91d-4f8f-a5be-f558a1f910cb)

This is the summary view, even after I refreshed the page. It appears to still show the older version of the RCI:

![Image](https://github.com/user-attachments/assets/2c8849d3-bf12-492b-8f02-86ccae945913)

**Comment by hamed-valiollahi** [comment]
Hi @Grulin , Thanks for reporting these issues. I’ll work on resolving them.

**Comment by Grulin** [comment]
Hi @hamed-valiollahi. Thanks for taking another look at this. I tested it using test account FS6 in dev using a 2024 report. The first adjustment I mentioned has been fixed, but I am still seeing a difference between the export input grid and the materialized view of the export section on the compliance report main page. I originally input a date that resulted in a correct RCI of -20, then added a new fuel code with a lower CI. This worked correctly again and pulled the new lower fuel code (-28), but still shows a difference between the input grid and the view on the main report page. 

Also important to note, it is saving the new lower CI value in the input grid of the export section, but the calculation is not updating with the new RCI on the edited line. In the example I used, the RCI being -20 would result in compliance units of -3514. With an updated RCI of -28, the compliance units should be -3799. It will only update when I delete the entire row and input it again, not if I edit the existing row.

**Comment by hamed-valiollahi** [comment]
Good morning @Grulin , Thanks so much for the thorough testing! This should be all set once the PR is merged. RCI and compliance units will automatically recalculate when you make any changes to the row.

**Comment by airinggov** [comment]
Looks great

**Comment by hamed-valiollahi** [comment]
Thanks @airinggov for testing! 🙏
